# Generated by Django 5.0.6 on 2024-05-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0002_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='jti',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
