# Generated by Django 5.0.6 on 2024-05-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0003_users_gender_alter_accesstoken_jti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='fname',
        ),
    ]
