# Generated by Django 5.0.6 on 2024-05-16 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('further_readings', models.CharField(max_length=200)),
                ('authorname', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('modifiedBy', models.CharField(max_length=50, null=True)),
                ('totalLikes', models.IntegerField(default=0)),
                ('totalComments', models.IntegerField(default=0)),
                ('authorid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
