# Generated by Django 5.0.6 on 2024-05-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='created_at',
        ),
    ]
