# Generated by Django 5.0.6 on 2024-05-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_articles_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='categoryname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
